[program:image-classification-api]
directory=/opt/image-classification-api
command=/opt/image-classification-api/venv/bin/python main.py
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/image-classification-api.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PATH="/opt/image-classification-api/venv/bin"

[program:image-classification-api-gunicorn]
directory=/opt/image-classification-api
command=/opt/image-classification-api/venv/bin/gunicorn main:app --bind 0.0.0.0:8001 --workers 2 --worker-class uvicorn.workers.UvicornWorker --timeout 300 --keep-alive 2
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/image-classification-api-gunicorn.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PATH="/opt/image-classification-api/venv/bin"
